/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;
import App.App;
import Classes.Neurona;
import Classes.Sinapsis;
import Controllers.ZonasAisladas;
import Controllers.SimuladorFlujo;
import LinkedList.LinkedList;
import LinkedList.ListNode;
import javax.swing.JOptionPane;
import org.graphstream.graph.*;
import org.graphstream.graph.implementations.*;
import org.graphstream.ui.swing_viewer.*;
import org.graphstream.ui.view.*;

/**
 *
 * @author  e miquilareno 2
 */
public class VisualizadorGrafo extends javax.swing.JFrame {
    private Viewer viewer;
    private LinkedList<String> rutaDijkstra;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VisualizadorGrafo.class.getName());

    /**
     * Creates new form VisualizadorGrafo
     */
    public VisualizadorGrafo() {
        initComponents();
         mostrarGrafo();
         jTextArea1.setEditable(false);
         jTextField2.setEditable(false);
    }

    private void mostrarGrafo() {
    System.setProperty("org.graphstream.ui", "swing");
    Graph gsGraph = new SingleGraph("Red Sinaptica");
    
    // Se agregan los nodos con su color segun estado
    Neurona[] neuronas = App.getInstance().getGraph().getNeuronas();
    for (int i = 0; i < App.getInstance().getGraph().getCantNeuronas(); i++) {
        String id = neuronas[i].getId();
        gsGraph.addNode(id).setAttribute("ui.label", id);
        // Nodos aislados en rojo, normales en verde
        if (neuronas[i].isAislada()) {
            gsGraph.getNode(id).setAttribute("ui.style", "fill-color: red;");
        } else {
            gsGraph.getNode(id).setAttribute("ui.style", "fill-color: green;");
        }
    }
    
// Se resaltan en azul los nodos de la ruta Dijkstra
    if (rutaDijkstra != null) {
        ListNode<String> nodoRuta = rutaDijkstra.getpFirst();
        while (nodoRuta != null) {
            Node gsNodo = gsGraph.getNode(nodoRuta.getElement());
            if (gsNodo != null) {
                gsNodo.setAttribute("ui.style", "fill-color: blue;");
            }
            nodoRuta = nodoRuta.getpNext();
        }
    }
    
    // Se agregan las aristas
    for (int i = 0; i < App.getInstance().getGraph().getCantNeuronas(); i++) {
        String idOrigen = neuronas[i].getId();
        ListNode<Sinapsis> nodo = App.getInstance().getGraph().getAdyacentes(idOrigen).getpFirst();
        while (nodo != null) {
            String idDestino = nodo.getElement().getDestino().getId();
            gsGraph.addEdge(idOrigen + "-" + idDestino, idOrigen, idDestino, true);
            nodo = nodo.getpNext();
        }
    }
    
    // Primera vez se crea el viewer y se embebe en el panel
    if (viewer == null) {
        viewer = new SwingViewer(gsGraph, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
        viewer.enableAutoLayout();
        ViewPanel viewPanel = (ViewPanel) viewer.addDefaultView(false);
        viewPanel.setPreferredSize(jPanel1.getPreferredSize());
        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(viewPanel, java.awt.BorderLayout.CENTER);
        jPanel1.revalidate();
    } else {
        // Siguientes veces se destruye el viewer y se recrea
        viewer.close();
        viewer = null;
        viewer = new SwingViewer(gsGraph, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
        viewer.enableAutoLayout();
        ViewPanel viewPanel = (ViewPanel) viewer.addDefaultView(false);
        viewPanel.setPreferredSize(jPanel1.getPreferredSize());
        jPanel1.removeAll();
        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(viewPanel, java.awt.BorderLayout.CENTER);
        jPanel1.revalidate();
        jPanel1.repaint();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 259, Short.MAX_VALUE)
        );

        jButton1.setText("Volver");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Ejecutar BFS");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Ejecutar DFS");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jLabel1.setText("Recorrido BFS/DFS");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setText("Inserte una neurona fuente");

        jButton4.setText("Ejecutar Recorrido Dijkstra");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jTextField2.addActionListener(this::jTextField2ActionPerformed);

        jTextField3.addActionListener(this::jTextField3ActionPerformed);

        jTextField4.addActionListener(this::jTextField4ActionPerformed);

        jLabel3.setText("Neurona origen");

        jLabel4.setText("Neurona llegada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE))
                                            .addComponent(jButton1)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(153, 153, 153)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(137, 137, 137)
                                        .addComponent(jLabel2))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(31, 31, 31)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jButton4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addGap(7, 7, 7)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         String idFuente = jTextField1.getText().trim();
        if (idFuente.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el ID de la neurona fuente.");
            return;
        }
        if (App.getInstance().getGraph().getNeurona(idFuente) == null) {
            JOptionPane.showMessageDialog(this, "La neurona " + idFuente + " no existe.");
            return;
        }
        ZonasAisladas za = new ZonasAisladas(App.getInstance().getGraph());
        za.BFS(idFuente);
        mostrarGrafo();
        
        StringBuilder sb = new StringBuilder("Recorrido BFS desde " + idFuente + ":\n");
        ListNode<String> nodo = za.getRecorrido().getpFirst();
        while (nodo != null) {
            sb.append(nodo.getElement());
            if (nodo.getpNext() != null) sb.append(" → ");
            nodo = nodo.getpNext();
        }
        jTextArea1.setText(sb.toString());

        JOptionPane.showMessageDialog(this, "BFS ejecutado desde neurona " + idFuente);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String idFuente = jTextField1.getText().trim();
        if (idFuente.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el ID de la neurona fuente.");
            return;
        }
        if (App.getInstance().getGraph().getNeurona(idFuente) == null) {
            JOptionPane.showMessageDialog(this, "La neurona " + idFuente + " no existe.");
            return;
        }
        ZonasAisladas za = new ZonasAisladas(App.getInstance().getGraph());
        za.DFS(idFuente);
        mostrarGrafo();
        
        StringBuilder sb = new StringBuilder("Recorrido DFS desde " + idFuente + ":\n");
        ListNode<String> nodo = za.getRecorrido().getpFirst();
        while (nodo != null) {
            sb.append(nodo.getElement());
            if (nodo.getpNext() != null) sb.append(" → ");
            nodo = nodo.getpNext();
        }
        jTextArea1.setText(sb.toString());

        JOptionPane.showMessageDialog(this, "DFS ejecutado desde neurona " + idFuente);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String idOrigen = jTextField3.getText().trim();
        String idDestino = jTextField4.getText().trim();

        // Se valida que los campos no esten vacios
        if (idOrigen.isEmpty() || idDestino.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese neurona de salida y llegada.");
            return;
        }
        // Se valida que ambas neuronas existan
        if (App.getInstance().getGraph().getNeurona(idOrigen) == null) {
            JOptionPane.showMessageDialog(this, "La neurona " + idOrigen + " no existe.");
            return;
        }
        if (App.getInstance().getGraph().getNeurona(idDestino) == null) {
            JOptionPane.showMessageDialog(this, "La neurona " + idDestino + " no existe.");
            return;
        }
        // Se valida que ninguna este aislada
        if (App.getInstance().getGraph().getNeurona(idOrigen).isAislada()) {
            JOptionPane.showMessageDialog(this, "La neurona " + idOrigen + " esta aislada. No se puede ejecutar Dijkstra.");
            return;
        }
        if (App.getInstance().getGraph().getNeurona(idDestino).isAislada()) {
            JOptionPane.showMessageDialog(this, "La neurona " + idDestino + " esta aislada. No se puede ejecutar Dijkstra.");
            return;
        }
        // Se ejecuta Dijkstra
        SimuladorFlujo sf = new SimuladorFlujo(App.getInstance().getGraph(), App.getInstance().getHashTable());
        LinkedList<String> ruta = sf.getRuta(idOrigen, idDestino);
        double tiempo = sf.getTiempo(idOrigen, idDestino);

        // Si no hay ruta posible
        if (ruta.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No existe ruta entre " + idOrigen + " y " + idDestino);
            return;
        }

        // Se muestra la ruta en jTextField2
        StringBuilder sb = new StringBuilder("Ruta: ");
        ListNode<String> nodo = ruta.getpFirst();
        while (nodo != null) {
            sb.append(nodo.getElement());
            if (nodo.getpNext() != null) sb.append(" → ");
            nodo = nodo.getpNext();
        }
        sb.append("  |  Tiempo: ").append(String.format("%.4f", tiempo));
        jTextField2.setText(sb.toString());

        // Se actualiza el grafo resaltando la ruta en azul
        rutaDijkstra = ruta;
        mostrarGrafo();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VisualizadorGrafo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
