/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;
import App.App;
import Classes.Neurona;
import Classes.Sinapsis;
import Controllers.ZonasAisladas;
import LinkedList.ListNode;
import javax.swing.JOptionPane;
import org.graphstream.graph.*;
import org.graphstream.graph.implementations.*;
import org.graphstream.ui.swing_viewer.*;
import org.graphstream.ui.view.*;

/**
 *
 * @author  e miquilareno 2
 */
public class VisualizadorGrafo extends javax.swing.JFrame {
    private Viewer viewer;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VisualizadorGrafo.class.getName());

    /**
     * Creates new form VisualizadorGrafo
     */
    public VisualizadorGrafo() {
        initComponents();
         mostrarGrafo();
         jTextArea1.setEditable(false);
    }

    private void mostrarGrafo() {
        System.setProperty("org.graphstream.ui", "swing");
        Graph gsGraph = new SingleGraph("Red Sinaptica");

        // Se agregan los nodos con su color segun estado
        Neurona[] neuronas = App.getInstance().getGraph().getNeuronas();
        for (int i = 0; i < App.getInstance().getGraph().getCantNeuronas(); i++) {
            String id = neuronas[i].getId();
            gsGraph.addNode(id).setAttribute("ui.label", id);
            // Nodos aislados en rojo, normales en verde
            if (neuronas[i].isAislada()) {
                gsGraph.getNode(id).setAttribute("ui.style", "fill-color: red;");
            } else {
                gsGraph.getNode(id).setAttribute("ui.style", "fill-color: green;");
            }
        }

        // Se agregan las aristas
        for (int i = 0; i < App.getInstance().getGraph().getCantNeuronas(); i++) {
            String idOrigen = neuronas[i].getId();
            ListNode<Sinapsis> nodo = App.getInstance().getGraph().getAdyacentes(idOrigen).getpFirst();
            while (nodo != null) {
                String idDestino = nodo.getElement().getDestino().getId();
                gsGraph.addEdge(idOrigen + "-" + idDestino, idOrigen, idDestino, true);
                nodo = nodo.getpNext();
            }
        }

        // Primera vez se crea el viewer y se embebe en el panel
        if (viewer == null) {
            viewer = new SwingViewer(gsGraph, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
            viewer.enableAutoLayout();
            ViewPanel viewPanel = (ViewPanel) viewer.addDefaultView(false);
            viewPanel.setPreferredSize(jPanel1.getPreferredSize());
            jPanel1.setLayout(new java.awt.BorderLayout());
            jPanel1.add(viewPanel, java.awt.BorderLayout.CENTER);
            jPanel1.revalidate();
        } else {
            // Siguientes veces se destruye el viewer y se recrea
            viewer.close();
            viewer = null;
            viewer = new SwingViewer(gsGraph, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
            viewer.enableAutoLayout();
            ViewPanel viewPanel = (ViewPanel) viewer.addDefaultView(false);
            viewPanel.setPreferredSize(jPanel1.getPreferredSize());
            jPanel1.removeAll();
            jPanel1.setLayout(new java.awt.BorderLayout());
            jPanel1.add(viewPanel, java.awt.BorderLayout.CENTER);
            jPanel1.revalidate();
            jPanel1.repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
        );

        jButton1.setText("Volver");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Ejecutar BFS");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Ejecutar DFS");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jLabel1.setText("Recorrido BFS/DFS");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setText("Inserte una neurona fuente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField1))))
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(75, 75, 75))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(64, 64, 64))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         String idFuente = jTextField1.getText().trim();
        if (idFuente.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el ID de la neurona fuente.");
            return;
        }
        if (App.getInstance().getGraph().getNeurona(idFuente) == null) {
            JOptionPane.showMessageDialog(this, "La neurona " + idFuente + " no existe.");
            return;
        }
        ZonasAisladas za = new ZonasAisladas(App.getInstance().getGraph());
        za.BFS(idFuente);
        mostrarGrafo();
        
        StringBuilder sb = new StringBuilder("Recorrido BFS desde " + idFuente + ":\n");
        ListNode<String> nodo = za.getRecorrido().getpFirst();
        while (nodo != null) {
            sb.append(nodo.getElement());
            if (nodo.getpNext() != null) sb.append(" → ");
            nodo = nodo.getpNext();
        }
        jTextArea1.setText(sb.toString());

        JOptionPane.showMessageDialog(this, "BFS ejecutado desde neurona " + idFuente);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String idFuente = jTextField1.getText().trim();
        if (idFuente.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el ID de la neurona fuente.");
            return;
        }
        if (App.getInstance().getGraph().getNeurona(idFuente) == null) {
            JOptionPane.showMessageDialog(this, "La neurona " + idFuente + " no existe.");
            return;
        }
        ZonasAisladas za = new ZonasAisladas(App.getInstance().getGraph());
        za.DFS(idFuente);
        mostrarGrafo();
        
        StringBuilder sb = new StringBuilder("Recorrido DFS desde " + idFuente + ":\n");
        ListNode<String> nodo = za.getRecorrido().getpFirst();
        while (nodo != null) {
            sb.append(nodo.getElement());
            if (nodo.getpNext() != null) sb.append(" → ");
            nodo = nodo.getpNext();
        }
        jTextArea1.setText(sb.toString());

        JOptionPane.showMessageDialog(this, "DFS ejecutado desde neurona " + idFuente);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VisualizadorGrafo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
